- Creación de la tabla de componentes
CREATE TABLE componentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(50) NOT NULL UNIQUE,
  nombre VARCHAR(100) NOT NULL,
  categoria VARCHAR(50) NOT NULL,
  marca VARCHAR(50) NOT NULL,
  cantidad INT NOT NULL CHECK (cantidad >= 0),
  estado VARCHAR(30) NOT NULL,
  descripcion TEXT,
  fecha_registro TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS) para lectura/escritura pública en este proyecto escolar
ALTER TABLE componentes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso público de lectura" ON componentes FOR SELECT USING (true);
CREATE POLICY "Acceso público de inserción" ON componentes FOR INSERT WITH CHECK (true);
CREATE POLICY "Acceso público de actualización" ON componentes FOR UPDATE USING (true);
CREATE POLICY "Acceso público de eliminación" ON componentes FOR DELETE USING (true);